[context]
name         = "Alice"
layout_title = "Pixel"

[settings]
layout_file   = "./src/layout.html"
md_dir        = "./src/md/"
pages_dir     = "./pages"

# Debugging server
host = "0.0.0.0"
port = 8000 

# Tools path
renderer = "./bin/template-renderer"
md       = "./bin/md-to-html"

VERSION = "0.1.0"
