[context]
name         = "Alice"
layout_title = "Pixel"

style_css    = "/static/style.css" 

[settings]
layout_file   = "./src/layout.html"
md_dir        = "./src/md/"
pages_dir     = "./pages"
static_dir    = "./static"

# Debugging server
host = "localhost"
port = 3000

# Tools path
renderer = "./bin/template-renderer"
md       = "./bin/md-to-html"

VERSION = "0.2.0"
