[context]
name  = "Alice"
age   = 18

joker = "potato"

[settings]
layout_file   = "./layout.html"
md_dir        = "./src"
pages_dir     = "./pages"

# Debugging server
host = "0.0.0.0"
port = 8000 

# Tools path
renderer = "./bin/template-renderer"
md       = "./bin/md-to-html"

VERSION = "0.0.1"
